//! User-precinct interop (T.800 §A.6.1, §B.6).
//!
//! Verifies that the decoder honours non-default `Spprecinct[r]` (the
//! `(PPx, PPy)` pair per resolution carried in COD/COC). The tier-2
//! walker emits one packet per (component, resolution, precinct, layer)
//! tuple in the spec's progression order; with multiple precincts per
//! resolution all five Part-1 progression orders need that breakdown
//! to round-trip OPJ bit-exact.
//!
//! Fixtures (64×64 testsrc, generated by `opj_compress` with
//! `-n 4 -c "[16,16],[32,32],[32,32]"`):
//! - `opj64_prec_lrcp.j2k`   — LRCP, user precincts `r0=16x16,
//!   r1=32x32, r2=32x32, r3=16x16` (decoded against
//!   `opj64_prec_lrcp.pgm`).
//! - `opj64_prec_rpcl.j2k`   — RPCL with the same precinct layout.
//! - `opj64_prec_pcrl.j2k`   — PCRL with the same precinct layout.
//! - `opj64_prec_cprl.j2k`   — CPRL (single component → identical to
//!   PCRL but exercises the outer-component dispatch).
//!
//! Reference PGMs are `opj_decompress` output — the four progression
//! orders all decode to the same image, so we share one reference file.

use oxideav_core::CodecRegistry;
use oxideav_core::{CodecId, CodecParameters, Frame, Packet, TimeBase};

const LRCP_J2K: &[u8] = include_bytes!("fixtures/opj64_prec_lrcp.j2k");
const LRCP_PGM: &[u8] = include_bytes!("fixtures/opj64_prec_lrcp.pgm");
const RPCL_J2K: &[u8] = include_bytes!("fixtures/opj64_prec_rpcl.j2k");
const PCRL_J2K: &[u8] = include_bytes!("fixtures/opj64_prec_pcrl.j2k");
const CPRL_J2K: &[u8] = include_bytes!("fixtures/opj64_prec_cprl.j2k");

const RGB_LRCP_J2K: &[u8] = include_bytes!("fixtures/opj128_rgb_prec_lrcp.j2k");
const RGB_RLCP_J2K: &[u8] = include_bytes!("fixtures/opj128_rgb_prec_rlcp.j2k");
const RGB_RPCL_J2K: &[u8] = include_bytes!("fixtures/opj128_rgb_prec_rpcl.j2k");
const RGB_PCRL_J2K: &[u8] = include_bytes!("fixtures/opj128_rgb_prec_pcrl.j2k");
const RGB_CPRL_J2K: &[u8] = include_bytes!("fixtures/opj128_rgb_prec_cprl.j2k");

fn parse_pgm(bytes: &[u8]) -> (u32, u32, Vec<u8>) {
    assert_eq!(&bytes[0..2], b"P5");
    let mut i = 2usize;
    let mut toks: Vec<String> = Vec::new();
    while toks.len() < 3 {
        while i < bytes.len() && (bytes[i] == b'\n' || bytes[i] == b' ' || bytes[i] == b'\t') {
            i += 1;
        }
        if i < bytes.len() && bytes[i] == b'#' {
            while i < bytes.len() && bytes[i] != b'\n' {
                i += 1;
            }
            continue;
        }
        let start = i;
        while i < bytes.len()
            && bytes[i] != b'\n'
            && bytes[i] != b' '
            && bytes[i] != b'\t'
            && bytes[i] != b'#'
        {
            i += 1;
        }
        toks.push(String::from_utf8_lossy(&bytes[start..i]).into_owned());
    }
    i += 1;
    let w: u32 = toks[0].parse().unwrap();
    let h: u32 = toks[1].parse().unwrap();
    (w, h, bytes[i..].to_vec())
}

fn decode_j2k(bytes: &[u8]) -> oxideav_core::VideoFrame {
    let mut reg = CodecRegistry::new();
    oxideav_jpeg2000::register(&mut reg);
    let params = CodecParameters::video(CodecId::new(oxideav_jpeg2000::CODEC_ID_STR));
    let mut dec = reg.make_decoder(&params).expect("factory");
    let pkt = Packet::new(0, TimeBase::new(1, 1), bytes.to_vec());
    dec.send_packet(&pkt).expect("send_packet");
    match dec.receive_frame().expect("receive_frame") {
        Frame::Video(v) => v,
        _ => panic!("expected video frame"),
    }
}

fn assert_bit_exact(name: &str, j2k: &[u8], pgm: &[u8]) {
    let (w, h, expected) = parse_pgm(pgm);
    assert_eq!((w, h), (64, 64), "{name}: unexpected fixture dims");
    let vf = decode_j2k(j2k);
    let got = &vf.planes[0].data;
    let nmismatch = expected
        .iter()
        .zip(got.iter())
        .filter(|(a, b)| a != b)
        .count();
    eprintln!("{name}: {nmismatch}/{} mismatches", expected.len());
    assert_eq!(nmismatch, 0, "{name}: not bit-exact");
}

#[test]
fn opj_user_precincts_lrcp_decodes_bit_exactly() {
    assert_bit_exact("opj64_prec_lrcp", LRCP_J2K, LRCP_PGM);
}

#[test]
fn opj_user_precincts_rpcl_decodes_bit_exactly() {
    assert_bit_exact("opj64_prec_rpcl", RPCL_J2K, LRCP_PGM);
}

#[test]
fn opj_user_precincts_pcrl_decodes_bit_exactly() {
    assert_bit_exact("opj64_prec_pcrl", PCRL_J2K, LRCP_PGM);
}

#[test]
fn opj_user_precincts_cprl_decodes_bit_exactly() {
    assert_bit_exact("opj64_prec_cprl", CPRL_J2K, LRCP_PGM);
}

// --- 128x128 RGB fixtures: -n 5 -c "[8,8],[16,16],[32,32],[32,32]" ---
// Five resolutions, four user-precinct records (the lowest resolution
// reuses the last). The encoder applies forward RCT (`MCT=1`) per
// component, so the precinct walker must also handle non-degenerate
// component interleaving in the position-driven progression orders.

// For the 3-component fixtures we use a relative cross-check: all five
// progression orders encode the *same* image, so their decoded planes
// must be identical to one another regardless of how the
// (component, resolution, precinct) tuples were interleaved in the
// codestream. Pure absolute equality with the OPJ-decoded PPM would
// also test our DC-shift / inverse-RCT path, which the dedicated
// `roundtrip_53` and existing OPJ interop tests already cover.

fn decode_planes(bytes: &[u8]) -> Vec<Vec<u8>> {
    let vf = decode_j2k(bytes);
    vf.planes.into_iter().map(|p| p.data).collect()
}

fn assert_planes_equal(name: &str, a: &[Vec<u8>], b: &[Vec<u8>]) {
    assert_eq!(a.len(), b.len(), "{name}: plane count mismatch");
    for (i, (pa, pb)) in a.iter().zip(b.iter()).enumerate() {
        assert_eq!(pa.len(), pb.len(), "{name}: plane {i} length");
        let nmismatch = pa.iter().zip(pb.iter()).filter(|(x, y)| x != y).count();
        assert_eq!(
            nmismatch, 0,
            "{name}: plane {i} differs in {nmismatch} samples"
        );
    }
}

#[test]
fn opj_rgb_precincts_all_orders_agree() {
    let lrcp = decode_planes(RGB_LRCP_J2K);
    for (name, j2k) in [
        ("rlcp", RGB_RLCP_J2K),
        ("rpcl", RGB_RPCL_J2K),
        ("pcrl", RGB_PCRL_J2K),
        ("cprl", RGB_CPRL_J2K),
    ] {
        let other = decode_planes(j2k);
        assert_planes_equal(name, &lrcp, &other);
    }
}

// --- 128x128 RGB, 64x64 tiles, user precincts ---
// Exercises the multi-tile decode path (`decode_frame` walks four tiles
// and re-applies the per-tile precinct partition for each one) jointly
// with all five progression orders.

const TILED_LRCP_J2K: &[u8] = include_bytes!("fixtures/opj128_tiled_prec_lrcp.j2k");
const TILED_RLCP_J2K: &[u8] = include_bytes!("fixtures/opj128_tiled_prec_rlcp.j2k");
const TILED_RPCL_J2K: &[u8] = include_bytes!("fixtures/opj128_tiled_prec_rpcl.j2k");
const TILED_PCRL_J2K: &[u8] = include_bytes!("fixtures/opj128_tiled_prec_pcrl.j2k");
const TILED_CPRL_J2K: &[u8] = include_bytes!("fixtures/opj128_tiled_prec_cprl.j2k");

#[test]
fn opj_tiled_rgb_precincts_all_orders_agree() {
    let lrcp = decode_planes(TILED_LRCP_J2K);
    for (name, j2k) in [
        ("rlcp", TILED_RLCP_J2K),
        ("rpcl", TILED_RPCL_J2K),
        ("pcrl", TILED_PCRL_J2K),
        ("cprl", TILED_CPRL_J2K),
    ] {
        let other = decode_planes(j2k);
        assert_planes_equal(name, &lrcp, &other);
    }
}

// --- 128x128 grayscale, 64x64 tiles, user precincts ---
// Absolute bit-exact comparison: four tiles each with their own
// precinct partition, decoded against `opj_decompress`. Catches
// per-tile precinct origin / cblk-state-leak regressions in the
// multi-tile driver.

const GRAY_TILED_PGM: &[u8] = include_bytes!("fixtures/opj128_gray_tiled_prec.pgm");
const GRAY_TILED_LRCP_J2K: &[u8] = include_bytes!("fixtures/opj128_gray_tiled_prec_lrcp.j2k");
const GRAY_TILED_RLCP_J2K: &[u8] = include_bytes!("fixtures/opj128_gray_tiled_prec_rlcp.j2k");
const GRAY_TILED_RPCL_J2K: &[u8] = include_bytes!("fixtures/opj128_gray_tiled_prec_rpcl.j2k");
const GRAY_TILED_PCRL_J2K: &[u8] = include_bytes!("fixtures/opj128_gray_tiled_prec_pcrl.j2k");
const GRAY_TILED_CPRL_J2K: &[u8] = include_bytes!("fixtures/opj128_gray_tiled_prec_cprl.j2k");

fn assert_gray_bit_exact(name: &str, j2k: &[u8], pgm: &[u8]) {
    let (w, h, expected) = parse_pgm(pgm);
    assert_eq!((w, h), (128, 128), "{name}: unexpected fixture dims");
    let vf = decode_j2k(j2k);
    let got = &vf.planes[0].data;
    let nmismatch = expected
        .iter()
        .zip(got.iter())
        .filter(|(a, b)| a != b)
        .count();
    eprintln!("{name}: {nmismatch}/{} mismatches", expected.len());
    assert_eq!(nmismatch, 0, "{name}: not bit-exact");
}

#[test]
fn opj_gray_tiled_precincts_lrcp_decodes_bit_exactly() {
    assert_gray_bit_exact(
        "opj128_gray_tiled_prec_lrcp",
        GRAY_TILED_LRCP_J2K,
        GRAY_TILED_PGM,
    );
}

#[test]
fn opj_gray_tiled_precincts_rlcp_decodes_bit_exactly() {
    assert_gray_bit_exact(
        "opj128_gray_tiled_prec_rlcp",
        GRAY_TILED_RLCP_J2K,
        GRAY_TILED_PGM,
    );
}

#[test]
fn opj_gray_tiled_precincts_rpcl_decodes_bit_exactly() {
    assert_gray_bit_exact(
        "opj128_gray_tiled_prec_rpcl",
        GRAY_TILED_RPCL_J2K,
        GRAY_TILED_PGM,
    );
}

#[test]
fn opj_gray_tiled_precincts_pcrl_decodes_bit_exactly() {
    assert_gray_bit_exact(
        "opj128_gray_tiled_prec_pcrl",
        GRAY_TILED_PCRL_J2K,
        GRAY_TILED_PGM,
    );
}

#[test]
fn opj_gray_tiled_precincts_cprl_decodes_bit_exactly() {
    assert_gray_bit_exact(
        "opj128_gray_tiled_prec_cprl",
        GRAY_TILED_CPRL_J2K,
        GRAY_TILED_PGM,
    );
}

// --- 128x128 grayscale lossy 9/7, 3 layers, user precincts ---
// Multi-layer interaction with the precinct walker: layer N's packets
// are interleaved across all (component, resolution, precinct) tuples
// per LRCP's outer-most loop, while the position-driven orders flip
// the (precinct, layer) order. The 9/7 path also exercises floating-
// point dequantisation per sub-band.

const ML_PREC_PGM: &[u8] = include_bytes!("fixtures/opj128_ml_prec.pgm");
const ML_PREC_LRCP_J2K: &[u8] = include_bytes!("fixtures/opj128_ml_prec_lrcp.j2k");
const ML_PREC_RLCP_J2K: &[u8] = include_bytes!("fixtures/opj128_ml_prec_rlcp.j2k");
const ML_PREC_RPCL_J2K: &[u8] = include_bytes!("fixtures/opj128_ml_prec_rpcl.j2k");
const ML_PREC_PCRL_J2K: &[u8] = include_bytes!("fixtures/opj128_ml_prec_pcrl.j2k");
const ML_PREC_CPRL_J2K: &[u8] = include_bytes!("fixtures/opj128_ml_prec_cprl.j2k");

#[test]
fn opj_multilayer_precincts_lrcp_decodes_bit_exactly() {
    assert_gray_bit_exact("opj128_ml_prec_lrcp", ML_PREC_LRCP_J2K, ML_PREC_PGM);
}

#[test]
fn opj_multilayer_precincts_rlcp_decodes_bit_exactly() {
    assert_gray_bit_exact("opj128_ml_prec_rlcp", ML_PREC_RLCP_J2K, ML_PREC_PGM);
}

#[test]
fn opj_multilayer_precincts_rpcl_decodes_bit_exactly() {
    assert_gray_bit_exact("opj128_ml_prec_rpcl", ML_PREC_RPCL_J2K, ML_PREC_PGM);
}

#[test]
fn opj_multilayer_precincts_pcrl_decodes_bit_exactly() {
    assert_gray_bit_exact("opj128_ml_prec_pcrl", ML_PREC_PCRL_J2K, ML_PREC_PGM);
}

#[test]
fn opj_multilayer_precincts_cprl_decodes_bit_exactly() {
    assert_gray_bit_exact("opj128_ml_prec_cprl", ML_PREC_CPRL_J2K, ML_PREC_PGM);
}
