//! RPCL progression-order interop (T.800 §B.12.1.3).
//!
//! Resolution-Position-Component-Layer ordering iterates outer in
//! resolution, then over (y, x) reference-grid coordinates that align
//! with each precinct, then component, then layer. With the default
//! precinct geometry (one precinct per resolution per component, set
//! by `Spprecinct = (15, 15)`) the position iteration collapses to a
//! single emission per (resolution, component) and the walk reduces
//! to `for r { for comp { for layer ... } }`.
//!
//! Fixtures (32x32 testsrc, generated by `opj_compress`):
//! - `opj32_rpcl.j2k`        — 4-res RPCL, 5/3 lossless, 1 layer.
//! - `opj32_3lyr_rpcl.j2k`   — 4-res RPCL, 5/3 lossless, 3 layers.
//!
//! References (`*.pgm`) are `opj_decompress` of the same codestreams.

use oxideav_core::CodecRegistry;
use oxideav_core::{CodecId, CodecParameters, Frame, Packet, TimeBase};

const SINGLE_J2K: &[u8] = include_bytes!("fixtures/opj32_rpcl.j2k");
const SINGLE_PGM: &[u8] = include_bytes!("fixtures/opj32_rpcl.pgm");
const ML_J2K: &[u8] = include_bytes!("fixtures/opj32_3lyr_rpcl.j2k");
const ML_PGM: &[u8] = include_bytes!("fixtures/opj32_3lyr_rpcl.pgm");

fn parse_pgm(bytes: &[u8]) -> (u32, u32, Vec<u8>) {
    assert_eq!(&bytes[0..2], b"P5");
    let mut i = 2usize;
    let mut toks: Vec<String> = Vec::new();
    while toks.len() < 3 {
        while i < bytes.len() && (bytes[i] == b'\n' || bytes[i] == b' ' || bytes[i] == b'\t') {
            i += 1;
        }
        if i < bytes.len() && bytes[i] == b'#' {
            while i < bytes.len() && bytes[i] != b'\n' {
                i += 1;
            }
            continue;
        }
        let start = i;
        while i < bytes.len()
            && bytes[i] != b'\n'
            && bytes[i] != b' '
            && bytes[i] != b'\t'
            && bytes[i] != b'#'
        {
            i += 1;
        }
        toks.push(String::from_utf8_lossy(&bytes[start..i]).into_owned());
    }
    i += 1;
    let w: u32 = toks[0].parse().unwrap();
    let h: u32 = toks[1].parse().unwrap();
    (w, h, bytes[i..].to_vec())
}

fn decode_j2k(bytes: &[u8]) -> oxideav_core::VideoFrame {
    let mut reg = CodecRegistry::new();
    oxideav_jpeg2000::register(&mut reg);
    let params = CodecParameters::video(CodecId::new(oxideav_jpeg2000::CODEC_ID_STR));
    let mut dec = reg.make_decoder(&params).expect("factory");
    let pkt = Packet::new(0, TimeBase::new(1, 1), bytes.to_vec());
    dec.send_packet(&pkt).expect("send_packet");
    match dec.receive_frame().expect("receive_frame") {
        Frame::Video(v) => v,
        _ => panic!("expected video frame"),
    }
}

fn assert_bit_exact(name: &str, j2k: &[u8], pgm: &[u8]) {
    let (w, h, expected) = parse_pgm(pgm);
    assert_eq!((w, h), (32, 32), "{name}: unexpected fixture dims");
    let vf = decode_j2k(j2k);
    let got = &vf.planes[0].data;
    let nmismatch = expected
        .iter()
        .zip(got.iter())
        .filter(|(a, b)| a != b)
        .count();
    eprintln!("{name}: {nmismatch}/{} mismatches", expected.len());
    assert_eq!(nmismatch, 0, "{name}: not bit-exact");
}

#[test]
fn opj_rpcl_single_layer_decodes_bit_exactly() {
    assert_bit_exact("opj32_rpcl", SINGLE_J2K, SINGLE_PGM);
}

#[test]
fn opj_rpcl_3layer_decodes_bit_exactly() {
    assert_bit_exact("opj32_3lyr_rpcl", ML_J2K, ML_PGM);
}
